"use strict";
exports.__esModule = true;
var factories_1 = require("./factories");
var lightThemeFactory = new factories_1.LightThemeFactory();
var darkThemeFactory = new factories_1.DarkThemeFactory();
var lightWarningButton = lightThemeFactory.createButton(true);
var darkWarningButton = darkThemeFactory.createButton(true);
var lightActiveButton = lightThemeFactory.createButton();
var darkActiveButton = darkThemeFactory.createButton();
var lightFullScreenModal = lightThemeFactory.createModalWindow(true);
var darkFullScreenModal = darkThemeFactory.createModalWindow(true);
var lightDefaultModal = lightThemeFactory.createModalWindow();
var darkDefaultModal = darkThemeFactory.createModalWindow();
lightWarningButton.showButtonDetails();
darkWarningButton.showButtonDetails();
lightActiveButton.showButtonDetails();
darkActiveButton.showButtonDetails();
lightFullScreenModal.showModalDetails();
darkFullScreenModal.showModalDetails();
lightDefaultModal.showModalDetails();
darkDefaultModal.showModalDetails();
