"use strict";
exports.__esModule = true;
var CarDirector_1 = require("./CarDirector");
var builders = require("./builders");
var fordBuilder = new builders.FordBuilder();
var audiBuilder = new builders.AudiBuilder();
var ferrariBuilder = new builders.FerrariBuilder();
var director = new CarDirector_1.CarDirector(fordBuilder);
director.buildCar();
var car1 = director.getCar();
director.setCarBuilder(audiBuilder);
director.buildCar();
var car2 = director.getCar();
director.setCarBuilder(ferrariBuilder);
director.buildCar();
var car3 = director.getCar();
car1.showDetails();
car2.showDetails();
car3.showDetails();
