"use strict";
exports.__esModule = true;
var models_1 = require("./models");
var Newspaper_1 = require("./Newspaper");
var newspaper = new Newspaper_1.Newspaper();
var admin = new models_1.Admin(newspaper);
var correspondentJohn = new models_1.Correspondent(newspaper, 'John');
var correspondentMatt = new models_1.Correspondent(newspaper, 'Matt');
var subscriberAlice = new models_1.Subscriber('Alice');
var subscriberMike = new models_1.Subscriber('Mike');
newspaper.subscribe(subscriberAlice);
admin.publishArticle('First article');
admin.updateMainArticle('First article');
correspondentJohn.publishArticle('John\'s article');
newspaper.subscribe(subscriberMike);
correspondentMatt.publishArticle('Matt\'s article');
newspaper.unsubscribe(subscriberAlice);
admin.removeArticle('First article');
admin.updateMainArticle('Matt\'s article');
